# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"example_func": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://wm-semeru.github.io/mlproj_template/"

git_url = "https://github.com/wm-semeru/mlproj_template/tree/main/"

def custom_doc_links(name): return None
